import pool from '../config/database.js';
import embeddingService from '../services/embeddingService.js';
import dotenv from 'dotenv';

dotenv.config();

const sampleJobs = [
  {
    title: 'Senior Full Stack Developer',
    company: 'TechCorp Solutions',
    description: 'We are seeking an experienced Full Stack Developer to join our dynamic team. You will work on building scalable web applications using modern technologies. The ideal candidate has strong experience in both frontend and backend development, with a passion for creating efficient, user-friendly solutions.',
    required_skills: ['JavaScript', 'React', 'Node.js', 'PostgreSQL', 'REST API'],
    preferred_skills: ['TypeScript', 'Docker', 'AWS', 'GraphQL', 'Redis'],
    experience_years: 5,
    location: 'San Francisco, CA (Hybrid)',
    salary_range: '$120,000 - $160,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Backend Developer (PHP/Laravel)',
    company: 'Digital Innovations Inc',
    description: 'Join our backend team to develop robust server-side applications. We need someone with strong PHP and Laravel experience who can design APIs, optimize database queries, and ensure application security. Experience with modern PHP practices and testing is essential.',
    required_skills: ['PHP', 'Laravel', 'MySQL', 'REST API', 'Git'],
    preferred_skills: ['Redis', 'Elasticsearch', 'PHPUnit', 'Docker', 'CI/CD'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$90,000 - $120,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Frontend Engineer (React)',
    company: 'StartupXYZ',
    description: 'We are looking for a talented Frontend Engineer to build beautiful, responsive user interfaces. You will work closely with designers and backend developers to create seamless user experiences. Strong React skills and attention to detail are must-haves.',
    required_skills: ['JavaScript', 'React', 'HTML', 'CSS', 'Redux'],
    preferred_skills: ['TypeScript', 'Next.js', 'Tailwind CSS', 'Jest', 'Webpack'],
    experience_years: 3,
    location: 'New York, NY',
    salary_range: '$100,000 - $140,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Python Developer (Django)',
    company: 'DataTech Labs',
    description: 'Seeking a Python developer with Django expertise to build data-driven web applications. You will work on APIs, data processing pipelines, and integrations with various data sources. Knowledge of data science libraries is a plus.',
    required_skills: ['Python', 'Django', 'PostgreSQL', 'REST API', 'Linux'],
    preferred_skills: ['Pandas', 'NumPy', 'Celery', 'Redis', 'AWS'],
    experience_years: 4,
    location: 'Austin, TX',
    salary_range: '$110,000 - $145,000',
    employment_type: 'Full-time',
  },
  {
    title: 'DevOps Engineer',
    company: 'CloudScale Systems',
    description: 'We need a DevOps Engineer to manage our cloud infrastructure and CI/CD pipelines. You will work on automating deployments, monitoring systems, and ensuring high availability. Strong experience with AWS and containerization is required.',
    required_skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Linux'],
    preferred_skills: ['Terraform', 'Ansible', 'Jenkins', 'Prometheus', 'Grafana'],
    experience_years: 4,
    location: 'Seattle, WA',
    salary_range: '$130,000 - $170,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Mobile App Developer (React Native)',
    company: 'MobileFirst Inc',
    description: 'Join our mobile team to build cross-platform applications using React Native. You will create high-performance mobile apps for iOS and Android, integrate with backend APIs, and ensure excellent user experience on mobile devices.',
    required_skills: ['JavaScript', 'React Native', 'REST API', 'iOS', 'Android'],
    preferred_skills: ['TypeScript', 'Redux', 'Firebase', 'GraphQL', 'App Store deployment'],
    experience_years: 3,
    location: 'Los Angeles, CA',
    salary_range: '$105,000 - $135,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Full Stack Engineer (MERN)',
    company: 'WebSolutions Pro',
    description: 'We are hiring a Full Stack Engineer proficient in the MERN stack. You will build modern web applications from the ground up, including database design, API development, and frontend implementation. Strong JavaScript knowledge is essential.',
    required_skills: ['MongoDB', 'Express', 'React', 'Node.js', 'JavaScript'],
    preferred_skills: ['TypeScript', 'Next.js', 'Redux', 'Docker', 'AWS'],
    experience_years: 4,
    location: 'Remote',
    salary_range: '$115,000 - $150,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Java Spring Boot Developer',
    company: 'Enterprise Solutions Ltd',
    description: 'Seeking an experienced Java developer with Spring Boot expertise to build enterprise-grade applications. You will work on microservices architecture, implement business logic, and ensure code quality through testing and best practices.',
    required_skills: ['Java', 'Spring Boot', 'MySQL', 'REST API', 'Microservices'],
    preferred_skills: ['Kafka', 'Redis', 'Docker', 'JUnit', 'AWS'],
    experience_years: 5,
    location: 'Boston, MA',
    salary_range: '$125,000 - $160,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Data Engineer',
    company: 'BigData Analytics',
    description: 'Join our data team to build and maintain data pipelines and infrastructure. You will work with large-scale data processing, ETL workflows, and data warehousing. Experience with distributed systems is highly valued.',
    required_skills: ['Python', 'SQL', 'Apache Spark', 'Kafka', 'Data Warehousing'],
    preferred_skills: ['AWS', 'Airflow', 'Hadoop', 'Scala', 'Terraform'],
    experience_years: 4,
    location: 'Chicago, IL',
    salary_range: '$120,000 - $155,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Junior Web Developer',
    company: 'CodeCraft Studios',
    description: 'Great opportunity for a junior developer to grow their skills! You will work on various web projects, learning from senior developers while contributing to real-world applications. We value enthusiasm and willingness to learn.',
    required_skills: ['HTML', 'CSS', 'JavaScript', 'Git', 'REST API'],
    preferred_skills: ['React', 'Node.js', 'SQL', 'TypeScript'],
    experience_years: 1,
    location: 'Remote',
    salary_range: '$60,000 - $80,000',
    employment_type: 'Full-time',
  },
  {
    title: '.NET Core Developer',
    company: 'Microsoft Partner Corp',
    description: 'Looking for a .NET Core developer to build enterprise applications. Work with C#, ASP.NET Core, and SQL Server. Experience with Azure cloud services is highly desirable. Join our team building mission-critical business applications.',
    required_skills: ['C#', 'ASP.NET Core', 'SQL Server', 'REST API', 'Entity Framework'],
    preferred_skills: ['Azure', 'Blazor', 'SignalR', 'Docker', 'Microservices'],
    experience_years: 4,
    location: 'Dallas, TX',
    salary_range: '$105,000 - $140,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Vue.js Frontend Developer',
    company: 'Modern Web Agency',
    description: 'Seeking a Vue.js specialist to create interactive web applications. You will work on component-based architecture, state management with Vuex, and integrate with RESTful APIs. Experience with Nuxt.js is a big plus.',
    required_skills: ['Vue.js', 'JavaScript', 'HTML', 'CSS', 'Vuex'],
    preferred_skills: ['Nuxt.js', 'TypeScript', 'SASS', 'Webpack', 'Jest'],
    experience_years: 3,
    location: 'Portland, OR',
    salary_range: '$95,000 - $125,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Ruby on Rails Developer',
    company: 'Rails Experts Inc',
    description: 'Join our Rails team to build scalable web applications. We need someone passionate about Ruby and Rails conventions. You will work on both legacy code modernization and new feature development. Experience with PostgreSQL required.',
    required_skills: ['Ruby', 'Rails', 'PostgreSQL', 'REST API', 'Git'],
    preferred_skills: ['Sidekiq', 'RSpec', 'Redis', 'Heroku', 'GraphQL'],
    experience_years: 4,
    location: 'Remote',
    salary_range: '$100,000 - $135,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Angular Developer',
    company: 'Enterprise Apps Co',
    description: 'We need an Angular expert to build complex single-page applications. Strong TypeScript skills required. You will work on large-scale enterprise applications with thousands of users. Experience with RxJS and NgRx is essential.',
    required_skills: ['Angular', 'TypeScript', 'RxJS', 'HTML', 'CSS'],
    preferred_skills: ['NgRx', 'Jest', 'Cypress', 'Material Design', 'Webpack'],
    experience_years: 4,
    location: 'Chicago, IL',
    salary_range: '$110,000 - $145,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Go Backend Engineer',
    company: 'High Performance Systems',
    description: 'Looking for a Go developer to build high-performance backend services. You will work on microservices, APIs, and distributed systems. Experience with concurrency patterns and performance optimization is crucial.',
    required_skills: ['Go', 'REST API', 'PostgreSQL', 'Microservices', 'Docker'],
    preferred_skills: ['gRPC', 'Kubernetes', 'Redis', 'RabbitMQ', 'AWS'],
    experience_years: 3,
    location: 'San Francisco, CA',
    salary_range: '$125,000 - $165,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Machine Learning Engineer',
    company: 'AI Innovations Lab',
    description: 'Join our ML team to build and deploy machine learning models. You will work on natural language processing, computer vision, and recommendation systems. Strong Python and ML framework experience required.',
    required_skills: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'NumPy'],
    preferred_skills: ['Keras', 'scikit-learn', 'Docker', 'AWS SageMaker', 'MLflow'],
    experience_years: 4,
    location: 'Boston, MA',
    salary_range: '$140,000 - $180,000',
    employment_type: 'Full-time',
  },
  {
    title: 'WordPress Developer',
    company: 'Content Management Solutions',
    description: 'Seeking a WordPress expert to develop custom themes and plugins. You will work with PHP, WordPress APIs, and modern JavaScript. Experience with WooCommerce and page builders like Elementor is valuable.',
    required_skills: ['WordPress', 'PHP', 'JavaScript', 'MySQL', 'HTML/CSS'],
    preferred_skills: ['WooCommerce', 'ACF', 'Elementor', 'REST API', 'React'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$75,000 - $100,000',
    employment_type: 'Full-time',
  },
  {
    title: 'iOS Developer (Swift)',
    company: 'Mobile Innovations Inc',
    description: 'Looking for an iOS developer to create native applications. Strong Swift and iOS SDK knowledge required. You will work on apps with millions of users, focusing on performance and user experience.',
    required_skills: ['Swift', 'iOS', 'Xcode', 'UIKit', 'REST API'],
    preferred_skills: ['SwiftUI', 'Combine', 'Core Data', 'Firebase', 'App Store Optimization'],
    experience_years: 4,
    location: 'Cupertino, CA',
    salary_range: '$120,000 - $155,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Android Developer (Kotlin)',
    company: 'Android Apps Studio',
    description: 'Join our Android team to build modern mobile applications. Kotlin expertise required. You will work on Material Design implementation, MVVM architecture, and integrate with various APIs and services.',
    required_skills: ['Kotlin', 'Android', 'Android Studio', 'REST API', 'Git'],
    preferred_skills: ['Jetpack Compose', 'Coroutines', 'Room', 'Retrofit', 'Firebase'],
    experience_years: 3,
    location: 'Austin, TX',
    salary_range: '$110,000 - $140,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Shopify Developer',
    company: 'E-commerce Experts',
    description: 'We need a Shopify developer to build and customize online stores. Strong Liquid templating and Shopify API knowledge required. You will create custom themes, apps, and integrations for various e-commerce clients.',
    required_skills: ['Shopify', 'Liquid', 'JavaScript', 'HTML', 'CSS'],
    preferred_skills: ['React', 'Node.js', 'Shopify Plus', 'GraphQL', 'Shopify API'],
    experience_years: 2,
    location: 'Remote',
    salary_range: '$80,000 - $110,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Rust Systems Engineer',
    company: 'Systems Software Corp',
    description: 'Looking for a Rust developer to work on systems programming. You will build high-performance, memory-safe applications. Experience with concurrent programming and low-level optimization is essential.',
    required_skills: ['Rust', 'Systems Programming', 'Linux', 'Git', 'Concurrency'],
    preferred_skills: ['WebAssembly', 'Async/Await', 'Docker', 'C++', 'Network Programming'],
    experience_years: 5,
    location: 'Seattle, WA',
    salary_range: '$145,000 - $185,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Scala Backend Developer',
    company: 'Functional Programming Inc',
    description: 'Join our Scala team to build scalable backend services. Strong functional programming skills required. You will work with Akka, Play Framework, and build reactive systems handling high traffic.',
    required_skills: ['Scala', 'Akka', 'Play Framework', 'REST API', 'PostgreSQL'],
    preferred_skills: ['Cats', 'ZIO', 'Kafka', 'Spark', 'Kubernetes'],
    experience_years: 4,
    location: 'New York, NY',
    salary_range: '$130,000 - $170,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Flutter Mobile Developer',
    company: 'Cross-Platform Apps',
    description: 'Seeking a Flutter developer to create beautiful mobile applications for iOS and Android. You will use Dart and Flutter framework to build performant cross-platform apps with native feel.',
    required_skills: ['Flutter', 'Dart', 'Mobile Development', 'REST API', 'Git'],
    preferred_skills: ['Firebase', 'Provider', 'Bloc', 'Material Design', 'App Store deployment'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$100,000 - $130,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Salesforce Developer',
    company: 'CRM Solutions Provider',
    description: 'Looking for a Salesforce developer to customize and extend Salesforce platform. Apex, Visualforce, and Lightning Component development experience required. You will build custom solutions for enterprise clients.',
    required_skills: ['Salesforce', 'Apex', 'Visualforce', 'Lightning Components', 'SOQL'],
    preferred_skills: ['Lightning Web Components', 'Salesforce DX', 'Integration', 'JavaScript', 'REST API'],
    experience_years: 3,
    location: 'Denver, CO',
    salary_range: '$95,000 - $125,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Data Scientist',
    company: 'Analytics Firm',
    description: 'Join our data science team to extract insights from large datasets. You will build predictive models, perform statistical analysis, and communicate findings to stakeholders. Strong Python and ML skills required.',
    required_skills: ['Python', 'Machine Learning', 'Statistics', 'Pandas', 'SQL'],
    preferred_skills: ['R', 'TensorFlow', 'Scikit-learn', 'Jupyter', 'Tableau'],
    experience_years: 4,
    location: 'San Diego, CA',
    salary_range: '$115,000 - $150,000',
    employment_type: 'Full-time',
  },
  {
    title: 'UI/UX Engineer',
    company: 'Design Tech Studio',
    description: 'Looking for a UI/UX Engineer who can both design and code. You will create beautiful interfaces and implement them using modern frontend technologies. Strong design sense and coding skills required.',
    required_skills: ['JavaScript', 'React', 'HTML', 'CSS', 'Figma'],
    preferred_skills: ['TypeScript', 'Sketch', 'Animation', 'Tailwind CSS', 'Design Systems'],
    experience_years: 3,
    location: 'Los Angeles, CA',
    salary_range: '$105,000 - $140,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Blockchain Developer',
    company: 'Crypto Innovations',
    description: 'Seeking a blockchain developer to build decentralized applications. Solidity and smart contract development experience required. You will work on DeFi protocols, NFT platforms, and Web3 integrations.',
    required_skills: ['Solidity', 'Ethereum', 'Smart Contracts', 'JavaScript', 'Web3.js'],
    preferred_skills: ['Hardhat', 'Truffle', 'React', 'IPFS', 'Blockchain Security'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$130,000 - $175,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Site Reliability Engineer',
    company: 'High Uptime Systems',
    description: 'Join our SRE team to ensure system reliability and performance. You will automate operations, monitor systems, and respond to incidents. Strong Linux, scripting, and cloud experience required.',
    required_skills: ['Linux', 'Python', 'Kubernetes', 'Monitoring', 'CI/CD'],
    preferred_skills: ['Prometheus', 'Grafana', 'Terraform', 'AWS', 'Go'],
    experience_years: 5,
    location: 'Seattle, WA',
    salary_range: '$135,000 - $175,000',
    employment_type: 'Full-time',
  },
  {
    title: 'QA Automation Engineer',
    company: 'Quality First Software',
    description: 'Looking for a QA Automation Engineer to build test frameworks. You will write automated tests, integrate with CI/CD pipelines, and ensure software quality. Experience with Selenium, Cypress, or Playwright required.',
    required_skills: ['JavaScript', 'Selenium', 'Test Automation', 'Git', 'CI/CD'],
    preferred_skills: ['Cypress', 'Playwright', 'Jest', 'Jenkins', 'Python'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$90,000 - $120,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Security Engineer',
    company: 'CyberSec Solutions',
    description: 'Join our security team to protect applications and infrastructure. You will perform security audits, implement security best practices, and respond to security incidents. Knowledge of OWASP and penetration testing required.',
    required_skills: ['Security', 'Penetration Testing', 'OWASP', 'Linux', 'Network Security'],
    preferred_skills: ['Python', 'Cloud Security', 'Cryptography', 'SIEM', 'Incident Response'],
    experience_years: 5,
    location: 'Washington, DC',
    salary_range: '$125,000 - $165,000',
    employment_type: 'Full-time',
  },
  {
    title: 'GraphQL API Developer',
    company: 'API First Company',
    description: 'Seeking a developer to build GraphQL APIs. You will design schemas, implement resolvers, and optimize query performance. Experience with Apollo Server and TypeScript strongly preferred.',
    required_skills: ['GraphQL', 'Node.js', 'TypeScript', 'REST API', 'Database'],
    preferred_skills: ['Apollo Server', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$110,000 - $145,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Embedded Systems Engineer',
    company: 'IoT Devices Inc',
    description: 'Looking for an embedded systems engineer to develop firmware for IoT devices. C/C++ programming and embedded Linux experience required. You will work on real-time systems and hardware interfaces.',
    required_skills: ['C', 'C++', 'Embedded Systems', 'Linux', 'Real-time OS'],
    preferred_skills: ['ARM', 'RTOS', 'I2C', 'SPI', 'UART'],
    experience_years: 5,
    location: 'San Jose, CA',
    salary_range: '$115,000 - $150,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Product Manager (Technical)',
    company: 'Product Led Growth Co',
    description: 'Seeking a technical product manager with engineering background. You will define product roadmaps, work with engineering teams, and drive product strategy. Strong technical understanding and communication skills required.',
    required_skills: ['Product Management', 'Agile', 'Technical Background', 'SQL', 'Analytics'],
    preferred_skills: ['Jira', 'Roadmapping', 'A/B Testing', 'Python', 'Data Analysis'],
    experience_years: 5,
    location: 'San Francisco, CA',
    salary_range: '$130,000 - $170,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Elixir/Phoenix Developer',
    company: 'Real-time Apps Inc',
    description: 'Join our Elixir team to build real-time, fault-tolerant applications. Experience with Phoenix Framework and functional programming required. You will work on systems requiring high concurrency and low latency.',
    required_skills: ['Elixir', 'Phoenix', 'PostgreSQL', 'REST API', 'Functional Programming'],
    preferred_skills: ['LiveView', 'Ecto', 'WebSockets', 'Docker', 'OTP'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$105,000 - $140,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Unity Game Developer',
    company: 'Game Studio XYZ',
    description: 'Looking for a Unity developer to create engaging games. C# and Unity3D experience required. You will work on game mechanics, physics, UI, and optimization for multiple platforms.',
    required_skills: ['Unity3D', 'C#', 'Game Development', '3D Graphics', 'Git'],
    preferred_skills: ['Shader Programming', 'Multiplayer', 'Mobile Optimization', 'AR/VR', 'Blender'],
    experience_years: 3,
    location: 'Los Angeles, CA',
    salary_range: '$95,000 - $130,000',
    employment_type: 'Full-time',
  },
  {
    title: 'SAP Developer',
    company: 'Enterprise ERP Solutions',
    description: 'Seeking an SAP developer to customize and extend SAP systems. ABAP programming experience required. You will develop custom modules, reports, and integrations for large enterprise clients.',
    required_skills: ['SAP', 'ABAP', 'SAP Modules', 'SQL', 'Business Logic'],
    preferred_skills: ['SAP HANA', 'Fiori', 'SAP BTP', 'OData', 'Integration'],
    experience_years: 4,
    location: 'Chicago, IL',
    salary_range: '$100,000 - $135,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Next.js Full Stack Developer',
    company: 'Modern Web Apps',
    description: 'Looking for a Next.js expert to build server-side rendered applications. You will work on both frontend and API routes, implement SEO optimization, and ensure performance. TypeScript experience required.',
    required_skills: ['Next.js', 'React', 'TypeScript', 'Node.js', 'REST API'],
    preferred_skills: ['Vercel', 'Prisma', 'tRPC', 'Tailwind CSS', 'PostgreSQL'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$110,000 - $145,000',
    employment_type: 'Full-time',
  },
  {
    title: 'ETL Developer',
    company: 'Data Integration Corp',
    description: 'Join our data team to build ETL pipelines. You will extract data from various sources, transform it, and load into data warehouses. Experience with Informatica, Talend, or similar tools required.',
    required_skills: ['ETL', 'SQL', 'Data Warehousing', 'Python', 'Database'],
    preferred_skills: ['Informatica', 'Talend', 'AWS Glue', 'Spark', 'Airflow'],
    experience_years: 4,
    location: 'Houston, TX',
    salary_range: '$100,000 - $130,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Technical Writer (Developer Docs)',
    company: 'API Documentation Co',
    description: 'Seeking a technical writer with coding background. You will write API documentation, tutorials, and guides. Strong writing skills and ability to understand complex technical concepts required.',
    required_skills: ['Technical Writing', 'API Documentation', 'Markdown', 'Git', 'Programming'],
    preferred_skills: ['JavaScript', 'Python', 'OpenAPI', 'Swagger', 'Docusaurus'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$85,000 - $115,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Cloud Architect',
    company: 'Cloud Native Solutions',
    description: 'Looking for a cloud architect to design scalable cloud solutions. AWS or Azure certification required. You will design architectures, set standards, and guide teams on cloud best practices.',
    required_skills: ['AWS', 'Cloud Architecture', 'Microservices', 'Kubernetes', 'Terraform'],
    preferred_skills: ['Azure', 'GCP', 'Service Mesh', 'Security', 'Cost Optimization'],
    experience_years: 7,
    location: 'San Francisco, CA',
    salary_range: '$150,000 - $200,000',
    employment_type: 'Full-time',
  },
  {
    title: 'NestJS Backend Developer',
    company: 'TypeScript Backend Co',
    description: 'Join our team to build enterprise-grade backend services with NestJS. Strong TypeScript and Node.js skills required. You will work on RESTful APIs, GraphQL, microservices, and database design.',
    required_skills: ['NestJS', 'TypeScript', 'Node.js', 'PostgreSQL', 'REST API'],
    preferred_skills: ['GraphQL', 'Microservices', 'Redis', 'Docker', 'TypeORM'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$105,000 - $140,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Business Intelligence Developer',
    company: 'BI Analytics Inc',
    description: 'Seeking a BI developer to create dashboards and reports. Experience with Power BI or Tableau required. You will work with stakeholders to understand requirements and build data visualizations.',
    required_skills: ['SQL', 'Power BI', 'Data Visualization', 'Data Analysis', 'ETL'],
    preferred_skills: ['Tableau', 'DAX', 'Python', 'Data Warehouse', 'Excel'],
    experience_years: 3,
    location: 'Atlanta, GA',
    salary_range: '$90,000 - $120,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Symfony PHP Developer',
    company: 'PHP Framework Experts',
    description: 'Looking for a Symfony developer to build robust web applications. Strong PHP and Symfony framework knowledge required. You will work on API development, database design, and backend services.',
    required_skills: ['PHP', 'Symfony', 'MySQL', 'REST API', 'Doctrine'],
    preferred_skills: ['API Platform', 'Redis', 'RabbitMQ', 'Docker', 'PostgreSQL'],
    experience_years: 4,
    location: 'Remote',
    salary_range: '$95,000 - $125,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Computer Vision Engineer',
    company: 'Vision AI Labs',
    description: 'Join our computer vision team to build AI-powered image analysis systems. You will work on object detection, image segmentation, and facial recognition. Strong Python and deep learning experience required.',
    required_skills: ['Python', 'Computer Vision', 'Deep Learning', 'TensorFlow', 'OpenCV'],
    preferred_skills: ['PyTorch', 'YOLO', 'CNN', 'Image Processing', 'CUDA'],
    experience_years: 4,
    location: 'Boston, MA',
    salary_range: '$130,000 - $170,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Svelte Frontend Developer',
    company: 'Lightweight Web Apps',
    description: 'Seeking a Svelte developer to build fast, reactive web applications. You will leverage Svelte\'s compile-time approach to create performant UIs. Experience with SvelteKit is highly desirable.',
    required_skills: ['Svelte', 'JavaScript', 'HTML', 'CSS', 'Git'],
    preferred_skills: ['SvelteKit', 'TypeScript', 'Tailwind CSS', 'REST API', 'WebSockets'],
    experience_years: 2,
    location: 'Remote',
    salary_range: '$90,000 - $120,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Penetration Tester',
    company: 'Ethical Hacking Services',
    description: 'Looking for a penetration tester to assess security vulnerabilities. You will perform security assessments, write detailed reports, and provide remediation recommendations. OSCP or similar certification preferred.',
    required_skills: ['Penetration Testing', 'Security', 'Linux', 'Network Security', 'Web Security'],
    preferred_skills: ['Metasploit', 'Burp Suite', 'Python', 'OSCP', 'Bug Bounty'],
    experience_years: 4,
    location: 'Remote',
    salary_range: '$110,000 - $145,000',
    employment_type: 'Full-time',
  },
  {
    title: 'FastAPI Python Developer',
    company: 'Modern API Solutions',
    description: 'Join our team to build high-performance APIs with FastAPI. You will create async APIs, implement authentication, integrate with databases, and write comprehensive documentation. Modern Python skills required.',
    required_skills: ['Python', 'FastAPI', 'PostgreSQL', 'REST API', 'Async/Await'],
    preferred_skills: ['SQLAlchemy', 'Pydantic', 'Docker', 'Redis', 'OAuth2'],
    experience_years: 3,
    location: 'Remote',
    salary_range: '$105,000 - $135,000',
    employment_type: 'Full-time',
  },
  {
    title: 'Kubernetes Platform Engineer',
    company: 'Container Orchestration Co',
    description: 'Seeking a Kubernetes expert to manage container platforms. You will design K8s clusters, implement CI/CD, manage helm charts, and ensure platform reliability. Strong DevOps background required.',
    required_skills: ['Kubernetes', 'Docker', 'Linux', 'CI/CD', 'Helm'],
    preferred_skills: ['Istio', 'Prometheus', 'ArgoCD', 'Terraform', 'AWS EKS'],
    experience_years: 5,
    location: 'Seattle, WA',
    salary_range: '$135,000 - $175,000',
    employment_type: 'Full-time',
  },
];

async function seedJobs() {
  const client = await pool.connect();

  try {
    console.log('Starting job seeding process...\n');

    // Clear existing jobs
    console.log('Clearing existing jobs...');
    await client.query('TRUNCATE TABLE jobs CASCADE;');
    console.log('✓ Existing jobs cleared\n');

    // Insert jobs with embeddings
    for (let i = 0; i < sampleJobs.length; i++) {
      const job = sampleJobs[i];
      console.log(`[${i + 1}/${sampleJobs.length}] Processing: ${job.title} at ${job.company}`);

      // Create text representation for embedding
      const jobText = embeddingService.createJobText(job);
      
      // Generate embedding
      console.log('  → Generating embedding...');
      const embedding = await embeddingService.createEmbedding(jobText);

      // Insert job
      console.log('  → Inserting into database...');
      const query = `
        INSERT INTO jobs (
          title, company, description, required_skills, preferred_skills,
          experience_years, location, salary_range, employment_type, embedding
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
        RETURNING id;
      `;

      const values = [
        job.title,
        job.company,
        job.description,
        job.required_skills,
        job.preferred_skills || null,
        job.experience_years,
        job.location,
        job.salary_range,
        job.employment_type,
        JSON.stringify(embedding),
      ];

      const result = await client.query(query, values);
      console.log(`  ✓ Job inserted with ID: ${result.rows[0].id}\n`);

      // Small delay to avoid rate limiting
      await new Promise(resolve => setTimeout(resolve, 500));
    }

    console.log('═══════════════════════════════════════════════');
    console.log(`✅ Successfully seeded ${sampleJobs.length} jobs!`);
    console.log('═══════════════════════════════════════════════\n');

  } catch (error) {
    console.error('❌ Error seeding jobs:', error);
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

// Run seeding
seedJobs().catch(console.error);

